name: Update Codeforces Stats

on:
  schedule:
    - cron: '0 12 * * *'  # runs every day at 12:00 UTC
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install requests
        run: pip install requests

      - name: Run update script
        run: python update_codeforces_stats.py

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add CODEFORCES_STATS.md
          git commit -m "Update Codeforces stats"
          git push
        continue-on-error: true
